plugins {
id 'com.android.application'

}

android {
namespace "duress.keyboard.lite"
compileSdk 29

buildFeatures {
        buildConfig true
}

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "duress.keyboard.lite"  
    minSdk 29
    targetSdk 37
    versionCode 15
    versionName "15.0"  
    manifestPlaceholders = [versionCode: versionCode]    
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}

}

dependencies {
}
